export const getMoviesMock = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/gG9fTyDL03fiKnOpf2tr01sncnt.jpg',
      genre_ids: [28, 878, 14],
      id: 526896,
      original_language: 'en',
      original_title: 'Morbius',
      overview:
        'Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.',
      popularity: 12394.971,
      poster_path: '/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg',
      release_date: '2022-03-30',
      title: 'Morbius',
      video: false,
      vote_average: 6.4,
      vote_count: 1052,
    },
    {
      adult: false,
      backdrop_path: '/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg',
      genre_ids: [28, 12, 35, 10749],
      id: 752623,
      original_language: 'en',
      original_title: 'The Lost City',
      overview:
        'A reclusive romance novelist was sure nothing could be worse than getting stuck on a book tour with her cover model until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.',
      popularity: 11308.998,
      poster_path: '/neMZH82Stu91d3iqvLdNQfqPPyl.jpg',
      release_date: '2022-03-24',
      title: 'The Lost City',
      video: false,
      vote_average: 6.8,
      vote_count: 714,
    },
    {
      adult: false,
      backdrop_path: '/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg',
      genre_ids: [28, 878, 35, 10751, 12],
      id: 675353,
      original_language: 'en',
      original_title: 'Sonic the Hedgehog 2',
      overview:
        'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
      popularity: 8887.435,
      poster_path: '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
      release_date: '2022-03-30',
      title: 'Sonic the Hedgehog 2',
      video: false,
      vote_average: 7.7,
      vote_count: 1569,
    },
    {
      adult: false,
      backdrop_path: '/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg',
      genre_ids: [28, 12, 14, 53],
      id: 639933,
      original_language: 'en',
      original_title: 'The Northman',
      overview:
        "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
      popularity: 7821.905,
      poster_path: '/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg',
      release_date: '2022-04-07',
      title: 'The Northman',
      video: false,
      vote_average: 7.5,
      vote_count: 1046,
    },
    {
      adult: false,
      backdrop_path: '/jCDycDqFJ1dIv5iJfTfub2h4ZAB.jpg',
      genre_ids: [27],
      id: 836225,
      original_language: 'en',
      original_title: 'The Exorcism of God',
      overview:
        'An American priest working in Mexico is considered a saint by many local parishioners. However, due to a botched exorcism, he carries a secret that’s eating him alive until he gets an opportunity to face his demon one final time.',
      popularity: 4761.952,
      poster_path: '/hangTmbxpSV4gpHG7MgSlCWSSFa.jpg',
      release_date: '2022-02-10',
      title: 'The Exorcism of God',
      video: false,
      vote_average: 7,
      vote_count: 162,
    },
    {
      adult: false,
      backdrop_path: '/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg',
      genre_ids: [28, 12],
      id: 335787,
      original_language: 'en',
      original_title: 'Uncharted',
      overview:
        'A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.',
      popularity: 4435.711,
      poster_path: '/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg',
      release_date: '2022-02-10',
      title: 'Uncharted',
      video: false,
      vote_average: 7.2,
      vote_count: 2068,
    },
    {
      adult: false,
      backdrop_path: '/xHrp2pq73oi9D64xigPjWW1wcz1.jpg',
      genre_ids: [80, 9648, 53],
      id: 414906,
      original_language: 'en',
      original_title: 'The Batman',
      overview:
        'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
      popularity: 4223.518,
      poster_path: '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
      release_date: '2022-03-01',
      title: 'The Batman',
      video: false,
      vote_average: 7.8,
      vote_count: 4720,
    },
    {
      adult: false,
      backdrop_path: '/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg',
      genre_ids: [14, 28, 12],
      id: 453395,
      original_language: 'en',
      original_title: 'Doctor Strange in the Multiverse of Madness',
      overview:
        'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
      popularity: 3992.478,
      poster_path: '/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
      release_date: '2022-05-04',
      title: 'Doctor Strange in the Multiverse of Madness',
      video: false,
      vote_average: 7.4,
      vote_count: 1789,
    },
    {
      adult: false,
      backdrop_path: '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
      genre_ids: [28, 12, 878],
      id: 634649,
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      overview:
        'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      popularity: 3856.503,
      poster_path: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
      release_date: '2021-12-15',
      title: 'Spider-Man: No Way Home',
      video: false,
      vote_average: 8.1,
      vote_count: 12964,
    },
    {
      adult: false,
      backdrop_path: '/fEe5fe82qHzjO4yej0o79etqsWV.jpg',
      genre_ids: [16, 35, 28, 10751, 80],
      id: 629542,
      original_language: 'en',
      original_title: 'The Bad Guys',
      overview:
        'When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.',
      popularity: 3566.389,
      poster_path: '/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg',
      release_date: '2022-03-17',
      title: 'The Bad Guys',
      video: false,
      vote_average: 7.8,
      vote_count: 476,
    },
    {
      adult: false,
      backdrop_path: '/figlwUsXXFehX3IebdjqNLV6vWk.jpg',
      genre_ids: [28, 53],
      id: 628900,
      original_language: 'en',
      original_title: 'The Contractor',
      overview:
        'After being involuntarily discharged from the U.S. Special Forces, James Harper decides to support his family by joining a private contracting organization alongside his best friend and under the command of a fellow veteran. Overseas on a covert mission, Harper must evade those trying to kill him while making his way back home.',
      popularity: 2994.133,
      poster_path: '/rJPGPZ5soaG27MK90oKpioSiJE2.jpg',
      release_date: '2022-03-10',
      title: 'The Contractor',
      video: false,
      vote_average: 6.6,
      vote_count: 245,
    },
    {
      adult: false,
      backdrop_path: '/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg',
      genre_ids: [16, 10751, 35, 14],
      id: 508947,
      original_language: 'en',
      original_title: 'Turning Red',
      overview:
        'Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.',
      popularity: 2926.126,
      poster_path: '/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg',
      release_date: '2022-03-10',
      title: 'Turning Red',
      video: false,
      vote_average: 7.5,
      vote_count: 2202,
    },
    {
      adult: false,
      backdrop_path: '/9Ngw106BLlNJ4iVpRHlrDfaLpCV.jpg',
      genre_ids: [878, 12, 28],
      id: 406759,
      original_language: 'en',
      original_title: 'Moonfall',
      overview:
        'A mysterious force knocks the moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.',
      popularity: 2800.264,
      poster_path: '/odVv1sqVs0KxBXiA8bhIBlPgalx.jpg',
      release_date: '2022-02-03',
      title: 'Moonfall',
      video: false,
      vote_average: 6.5,
      vote_count: 1076,
    },
    {
      adult: false,
      backdrop_path: '/wtbRUVxQVvU6QIJH1oGLDThJLib.jpg',
      genre_ids: [35, 28],
      id: 785985,
      original_language: 'fr',
      original_title: 'Loin du périph',
      overview:
        'Ousmane Diakité and François Monge are two cops with very different styles, backgrounds and careers. The unlikely pair are reunited once again for a new investigation that takes them across France. What seemed to be a simple drug deal turns out to be a much bigger criminal case wrapped in danger and unexpected comedy.',
      popularity: 2603.727,
      poster_path: '/h5hVeCfYSb8gIO0F41gqidtb0AI.jpg',
      release_date: '2022-05-06',
      title: 'The Takedown',
      video: false,
      vote_average: 5.8,
      vote_count: 143,
    },
    {
      adult: false,
      backdrop_path: '/i0zbSmiyyylh7H3Qb4jgscz46Pm.jpg',
      genre_ids: [27],
      id: 893370,
      original_language: 'es',
      original_title: 'Virus-32',
      overview: 'A virus is unleashed and a chilling massacre runs through the streets of Montevideo.',
      popularity: 2155.339,
      poster_path: '/wZiF79hbhLK1U2Pj9bF67NAKXQR.jpg',
      release_date: '2022-04-21',
      title: 'Virus:32',
      video: false,
      vote_average: 6.9,
      vote_count: 52,
    },
    {
      adult: false,
      backdrop_path: '/dW3fQJrshh2wYDoW4HUA7ZabsN1.jpg',
      genre_ids: [28, 53, 80],
      id: 763285,
      original_language: 'en',
      original_title: 'Ambulance',
      overview:
        "Decorated veteran Will Sharp, desperate for money to cover his wife's medical bills, asks for help from his adoptive brother Danny. A charismatic career criminal, Danny instead offers him a score: the biggest bank heist in Los Angeles history: $32 million.",
      popularity: 2112.163,
      poster_path: '/zT5ynZ0UR6HFfWQSRf2uKtqCyWD.jpg',
      release_date: '2022-03-16',
      title: 'Ambulance',
      video: false,
      vote_average: 7,
      vote_count: 630,
    },
    {
      adult: false,
      backdrop_path: '/eQN31P4IEhyp6NkdccvppJnyuJ4.jpg',
      genre_ids: [28, 12, 14, 878],
      id: 284052,
      original_language: 'en',
      original_title: 'Doctor Strange',
      overview:
        'After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.',
      popularity: 2090.057,
      poster_path: '/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg',
      release_date: '2016-10-25',
      title: 'Doctor Strange',
      video: false,
      vote_average: 7.4,
      vote_count: 19012,
    },
    {
      adult: false,
      backdrop_path: '/jIdZmqElYgNwlCsUtCwmN1rDu7I.jpg',
      genre_ids: [80, 18, 53],
      id: 799876,
      original_language: 'en',
      original_title: 'The Outfit',
      overview:
        'Leonard is an English tailor who used to craft suits on London’s world-famous Savile Row. After a personal tragedy, he’s ended up in Chicago, operating a small tailor shop in a rough part of town where he makes beautiful clothes for the only people around who can afford them: a family of vicious gangsters.',
      popularity: 1926.282,
      poster_path: '/lZa5EB6PVJBT5mxhgZS5ftqdAm6.jpg',
      release_date: '2022-02-25',
      title: 'The Outfit',
      video: false,
      vote_average: 7,
      vote_count: 225,
    },
    {
      adult: false,
      backdrop_path: '/qNRkfXBdAuXk9Qs3BEDIfmbAK9w.jpg',
      genre_ids: [80, 28],
      id: 883502,
      original_language: 'en',
      original_title: "Fortress: Sniper's Eye",
      overview:
        "Weeks after the deadly assault on Fortress Camp, Robert makes a daring rescue to save Sasha, the widow of his old nemesis Balzary. But back in the camp's command bunker, it appears Sasha may have devious plans of her own. As a new attack breaks out, Robert is confronted with a familiar face he thought he'd never see again…",
      popularity: 1831.292,
      poster_path: '/61J34xHVVdQHbJ4MSCWQo4e727v.jpg',
      release_date: '2022-04-29',
      title: "Fortress: Sniper's Eye",
      video: false,
      vote_average: 5.8,
      vote_count: 39,
    },
    {
      adult: false,
      backdrop_path: '/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg',
      genre_ids: [16, 35, 10751, 14],
      id: 568124,
      original_language: 'en',
      original_title: 'Encanto',
      overview:
        "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
      popularity: 1537.979,
      poster_path: '/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg',
      release_date: '2021-11-24',
      title: 'Encanto',
      video: false,
      vote_average: 7.7,
      vote_count: 6487,
    },
  ],
  total_pages: 33644,
  total_results: 672867,
}

export default vi.fn(() => Promise.resolve(getMoviesMock.results))
